//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetpetEv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_consulta
    {
        public int id_detalle { get; set; }
        public int id_hora { get; set; }
        public int id_mascota { get; set; }
        public string peso { get; set; }
        public string observación { get; set; }
        public string diagnostico { get; set; }
        public string receta { get; set; }
    
        public virtual Hora Hora { get; set; }
        public virtual Mascota Mascota { get; set; }
    }
}
