//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetpetEv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.Detalle_consulta = new HashSet<Detalle_consulta>();
        }
    
        public int id_mascota { get; set; }
        public int id_dueño { get; set; }
        public string nombre_mascota { get; set; }
        public string sexo { get; set; }
        public System.DateTime fecha_nac { get; set; }
        public int id_especie { get; set; }
        public int id_raza { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_consulta> Detalle_consulta { get; set; }
        public virtual Especie Especie { get; set; }
        public virtual Raza Raza { get; set; }
    }
}
